apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  name: task3-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: task3-webapp
              servicePort: 80
            path: /