apiVersion: apps/v1
kind: Deployment
metadata:
  name: task3-webapp
  labels:
    app: task3-webapp
  namespace: default
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: task3-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: task3-webapp
    spec:
      containers:
      - name: task3-webapp
        image: {{ .Values.python.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: task3-webapp
        ports:
        - containerPort: 5000
          protocol: TCP
